ASPKnowledgeBase/Controllers/AdminController.cs
using ASPKnowledgeBase.Models;
using DataAccess.Entities;
using Services.BuisnessLogic.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPKnowledgeBase.Controllers
{
    [Authorize(Users = "admin")]
    public class AdminController : Controller
    {
        IThemeService themeService = null;
        IQuestionLineService questionLineService = null;

        public AdminController(IThemeService themeService, IQuestionLineService questionLineService)
        {
            this.themeService = themeService;
            this.questionLineService = questionLineService;
        }

        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        #region Themes Methods

        public PartialViewResult GetThemes()
        {
            IEnumerable<Theme> themes = themeService.GetThemes();

            return PartialView("Modal/_Themes", themes);
        }

        public PartialViewResult EditTheme(int themeId)
        {
            return PartialView("Modal/_EditTheme", themeId);
        }

        public PartialViewResult GetTheme(int themeId)
        {
            Theme theme = themeService.GetTheme(themeId);

            return PartialView("Modal/_ThemePartial", theme);
        }

        [HttpPost]
        public ActionResult UpdateTheme(Theme theme)
        {
            if (ModelState.IsValid)
            {
                if (theme.Id == 0)
                {
                    themeService.AddTheme(theme);
                }

                themeService.UpdateTheme(theme);

                ViewBag.Message = "Изменения в теме были сохранены";

            }
            return PartialView("Modal/_ThemePartial", theme);
        }

        [HttpPost]
        public ActionResult AddTheme([Bind(Exclude = "Id")]Theme theme)
        {
            return UpdateTheme(theme);
        }

        [HttpPost]
        public PartialViewResult RemoveTheme(int themeId)
        {
            themeService.RemoveTheme(themeId);

            return GetThemes();
        }

        #endregion

        #region QuestionLines Methods

        public PartialViewResult GetQuestions()
        {
            //New questions are on the top
            IEnumerable<QuestionLine> questions = questionLineService.GetQuestionLines().OrderByDescending(x=>x.Id);

            return PartialView("Modal/_Questions", questions);
        }

        public PartialViewResult EditQuestion(int questionId)
        {
            return PartialView("Modal/_EditQuestion", questionId);
        }

        public PartialViewResult GetAnswer(int questionId)
        {
            QuestionLine question = questionLineService.GetQuestionLine(questionId);

            return PartialView("Modal/_QuestionPartial", question);
        }

        [HttpPost]
        public PartialViewResult UpdateQuestion(QuestionLine question)
        {
            QuestionLine refer = questionLineService.GetQuestionLine(question.Id);

            refer.IsPublic = question.IsPublic;

            refer.Answer = question.Answer;

            questionLineService.UpdateQuestionLine(refer);

            ViewBag.Message = "Изменения в вопросе были сохранены";

            return PartialView("Modal/_QuestionPartial", question);
        }
        #endregion
    }
}

ASPKnowledgeBase/Controllers/LoginController.cs
using ASPKnowledgeBase.Infrastructure.Base;
using ASPKnowledgeBase.Models.Login;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace ASPKnowledgeBase.Controllers
{
    public class LoginController : Controller
    {
        IAuthProvider authProvider;

        public LoginController(IAuthProvider authProvider)
        {
            this.authProvider = authProvider;
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult GetLoginState()
        {
            return PartialView("_LoginState");
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult LoginLink(string partial = "_LoginLink")
        {
            bool auth = System.Web.HttpContext.Current.User?.Identity.IsAuthenticated ?? false;

            if (auth)
            {
                var userName = Thread.CurrentPrincipal.Identity.Name;
                return PartialView(partial, new LoginLinkUser { IsLoggedIn = true, Login = userName });
            }
            return PartialView(partial, new LoginLinkUser { IsLoggedIn = false });
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult LoginModal(LoginUser user)
        {
            if (!string.IsNullOrWhiteSpace(user.UserName) &&
                !string.IsNullOrWhiteSpace(user.Password) &&
                ModelState.IsValid)
            {
                if (authProvider.Authenticate(user.UserName, user.Password))
                {
                    return PartialView("_LoginClosePartial");
                }
                else
                {
                    ModelState.AddModelError("Enter", "Неправильный логин или пароль");
                    return PartialView("_LoginInsidePartial", user);
                }
            }
            else
            {
                return PartialView("_LoginInsidePartial", user);
            }
        }

        public ActionResult Logout()
        {
            authProvider.SignOut();

            return RedirectToAction("Index", "Home");
        }
    }
}

ASPKnowledgeBase/Views/Shared/_AdminLink.cshtml
@model ASPKnowledgeBase.Models.Login.LoginLinkUser

@if (Model.IsLoggedIn && Model.Login == "admin")
{
    <a href="#" onclick="showAdminPanel()">Панель администратора</a>
}

ASPKnowledgeBase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#" onclick="showGuestPanel()">Главная</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right" id="loginState">
                    @Html.Action("GetLoginState", "Login")
                        
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="my-content">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Knowledge base. Be smarter</p>
        </footer>
    </div>

    @Html.Partial("_LoginPartial", new ASPKnowledgeBase.Models.Login.LoginUser())



    <script type="text/javascript">
    function showAdminPanel() {
            $.ajax({
                method: 'GET',
                data: null,
                url: '@Url.Action("Index", "Admin")',
                success: function (view) {
                    $('.my-content').empty().html(view);
            },
                error: function (err) {
                console.log('ERROR');
                console.log(err);
            }
            });
        }

        function showGuestPanel() {
            $.ajax({
                method: 'GET',
                data: null,
                url: '@Url.Action("ShowContent", "Home")',
                success: function (view) {
                    $('.my-content').empty().html(view);
            },
                error: function (err) {
                console.log('ERROR');
                console.log(err);
            }
            });
        }


        function getLoginState() {
        $.ajax({
            method: 'GET',
            data: null,
            url: '@Url.Action("GetLoginState", "Login")',
            success: function (view) {
                console.log('SUCCESS');
                $('#loginState').empty().html(view);
            },
            error: function (err) {
                console.log('ERROR');
                console.log(err);
            }
        });
    }
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ASPKnowledgeBase/Views/Shared/_LoginClosePartial.cshtml
<script>
    @*window.location.reload();*@
    $('#closeBtn').click();
    getLoginState();

</script>

ASPKnowledgeBase/Views/Shared/_LoginInsidePartial.cshtml
@model ASPKnowledgeBase.Models.Login.LoginUser

<div class="modal-body" id="refreshLogin">
    <div class="form-group">
        @Html.ValidationMessage("Enter")
    </div>
    <div class="form-group">
        <label for="UserName">Login</label>
        @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
        @Html.ValidationMessage("UserName", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label for="Password">Password</label>
        @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
        @Html.ValidationMessage("Password", new { @class = "text-danger" })
    </div>
</div>

ASPKnowledgeBase/Views/Shared/_LoginLink.cshtml
@model ASPKnowledgeBase.Models.Login.LoginLinkUser

@if (Model.IsLoggedIn)
{
    <li><a href="#">@Model.Login</a></li>
    <span>|</span>
    <li><a href="@Url.Action("Logout", "Login")">Выход</a></li>
}
else
{
    <li><span class="navbar-text">Гость</span></li>
    <span>|</span>
    <li><a href="#" data-toggle="modal" data-target="#loginModal">Войти</a></li>
}

ASPKnowledgeBase/Views/Shared/_UserAnswers.cshtml
@model IEnumerable<DataAccess.Entities.QuestionLine>

    
@if (Model.Count() != 0)
{
<table class="table table-bordered table-hover">
    <tr>
        <th>№</th>
        <th>Тема</th>
        <th>Автор</th>
        <th>Дата</th>
        <th>Вопрос</th>
        <th>Ответ</th>
    </tr>
    @foreach (var line in Model)
    {
        <tr>
            <td>@line.Id</td>
            <td>@line.Theme.Description</td>
            <td>@line.Author</td>
            <td>@line.Date</td>
            <td>@line.Question</td>
            <td>@line.Answer</td>
        </tr>
    }
</table>
}
else
{
<h4>Поиск не дал результатов</h4>
}

ASPKnowledgeBase/Views/Shared/_UserQuestionForm.cshtml
@model DataAccess.Entities.QuestionLine

<div id="userquestion">

    @if (ViewBag.SuccessMessage != null)
    {
        <div class="form-group">
            <div class="alert alert-success" id="result-message">@ViewBag.SuccessMessage</div>
        </div>
    }

    <div class="form-group">
        @Html.Label("Theme")
        @Html.DropDownListFor(x => x.ThemeId,
                                                  (ViewBag.Themes as IEnumerable<string>)
                                                  .Select((e, i) => new SelectListItem { Value = (i + 1).ToString(), Text = e }),
                                                  new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Author)
        @Html.TextBoxFor(x => x.Author, new { @class = "form-control", autocomplete = "off" })
        @Html.ValidationMessageFor(x => x.Author, null, new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Email)
        @Html.TextBoxFor(x => x.Email, new { @class = "form-control", autocomplete = "off" })
        @Html.ValidationMessageFor(x => x.Email, null, new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Question)
        @Html.TextAreaFor(x => x.Question, new { @class = "form-control", rows = 5, autocomplete = "off" })
        @Html.ValidationMessageFor(x => x.Question, null, new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Задать вопрос" />
    </div>

</div>


<script type="text/javascript">
    setTimeout(function () { $('#result-message').fadeOut('fast') }, 2000);
</script>